# Generated by Django 5.0.8 on 2024-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_testdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimage',
            name='image_name',
            field=models.CharField(default='default_image_name', max_length=100),
        ),
    ]
