# Generated by Django 5.0.8 on 2024-08-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profiledescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledescription',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
